### ISSUE TITLE
Please make a docker image available

### ISSUE THREAD

**Issue by AvMavs** [saleem-hadad/finance#32]
I'm a docker beginner, and while I do know my way around container deployment in general, the deployment process of this app (which is easily the most beautiful one for personal finance management) is a bit too complicated.

Could you make a docker image available for this, with a simplified docker-compose?

**Comment by saleem-hadad** [comment]
Thank you very much for your feedback @AvMavs. Yes, I agree with you and it's a TODO task I've on my list. I'll try to prioritize it for the upcoming days.

**Comment by AvMavs** [comment]
Thank you!

**Comment by AvMavs** [comment]
Can you release a ghcr.io or DockerHub image as well (if possible)?

**Comment by saleem-hadad** [comment]
yes sure

**Comment by saleem-hadad** [comment]
image uploaded to my docker hub account. 

try this docker-compose.yml file

```
version: '3'
services:
    app:
        image: 'salee2m1/finance:1.0.0'
        ports:
            - "80:80"
        networks:
            - finance
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'finance'
            MYSQL_USER: 'finance'
            MYSQL_PASSWORD: 'finance'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'financemysql:/var/lib/mysql'
        networks:
            - finance
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-proot"]
            retries: 3
            timeout: 5s
networks:
    finance:
        driver: bridge
volumes:
    financemysql:
        driver: local
```

then run the following commands in the same folder
```
docker-compose up -d
docker-compose run app php artisan migrate
docker-compose run app php artisan finance:install
```
